# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:      Coderdojo Athlone
copyright:  © 2019 - Coderdojo Athlone

description: >-
  Official page for Coderdojo Athlone.
  Come and join us on Saturday's and discover how to code and make games!

baseKeywords:
  - ait
  - arduino
  - association
  - athlone
  - code
  - coderdojo
  - coding
  - computer
  - css
  - development
  - discover
  - electronics
  - fun
  - game
  - git
  - html
  - javascript
  - kid
  - learn
  - mentor
  - mysql
  - php
  - project
  - python
  - raspberry
  - science
  - scratch
  - volunteer
  - web
  - westmeath

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  CoderdojoAthlone
github_repo:      'https://github.com/CoderdojoAthlone/coderdojoathlone.github.io'

google_analytics: UA-135278375-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
- Gemfile
- Gemfile.lock
- .idea
- scripts
- package**.json

sass:
  sass_dir: _sass
  style: compressed
